development:
  adapter: mysql2
  encoding: utf8
  database: eos_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  database: eos_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  
production:
  adapter: mysql2
  encoding: utf8
  database: eos_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *test