require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PercentageModifiersController do

  # This should return the minimal set of attributes required to create a valid
  # PercentageModifier. As you add validations to PercentageModifier, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PercentageModifiersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all percentage_modifiers as @percentage_modifiers" do
      percentage_modifier = PercentageModifier.create! valid_attributes
      get :index, {}, valid_session
      assigns(:percentage_modifiers).should eq([percentage_modifier])
    end
  end

  describe "GET show" do
    it "assigns the requested percentage_modifier as @percentage_modifier" do
      percentage_modifier = PercentageModifier.create! valid_attributes
      get :show, {:id => percentage_modifier.to_param}, valid_session
      assigns(:percentage_modifier).should eq(percentage_modifier)
    end
  end

  describe "GET new" do
    it "assigns a new percentage_modifier as @percentage_modifier" do
      get :new, {}, valid_session
      assigns(:percentage_modifier).should be_a_new(PercentageModifier)
    end
  end

  describe "GET edit" do
    it "assigns the requested percentage_modifier as @percentage_modifier" do
      percentage_modifier = PercentageModifier.create! valid_attributes
      get :edit, {:id => percentage_modifier.to_param}, valid_session
      assigns(:percentage_modifier).should eq(percentage_modifier)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PercentageModifier" do
        expect {
          post :create, {:percentage_modifier => valid_attributes}, valid_session
        }.to change(PercentageModifier, :count).by(1)
      end

      it "assigns a newly created percentage_modifier as @percentage_modifier" do
        post :create, {:percentage_modifier => valid_attributes}, valid_session
        assigns(:percentage_modifier).should be_a(PercentageModifier)
        assigns(:percentage_modifier).should be_persisted
      end

      it "redirects to the created percentage_modifier" do
        post :create, {:percentage_modifier => valid_attributes}, valid_session
        response.should redirect_to(PercentageModifier.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved percentage_modifier as @percentage_modifier" do
        # Trigger the behavior that occurs when invalid params are submitted
        PercentageModifier.any_instance.stub(:save).and_return(false)
        post :create, {:percentage_modifier => {}}, valid_session
        assigns(:percentage_modifier).should be_a_new(PercentageModifier)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PercentageModifier.any_instance.stub(:save).and_return(false)
        post :create, {:percentage_modifier => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested percentage_modifier" do
        percentage_modifier = PercentageModifier.create! valid_attributes
        # Assuming there are no other percentage_modifiers in the database, this
        # specifies that the PercentageModifier created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PercentageModifier.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => percentage_modifier.to_param, :percentage_modifier => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested percentage_modifier as @percentage_modifier" do
        percentage_modifier = PercentageModifier.create! valid_attributes
        put :update, {:id => percentage_modifier.to_param, :percentage_modifier => valid_attributes}, valid_session
        assigns(:percentage_modifier).should eq(percentage_modifier)
      end

      it "redirects to the percentage_modifier" do
        percentage_modifier = PercentageModifier.create! valid_attributes
        put :update, {:id => percentage_modifier.to_param, :percentage_modifier => valid_attributes}, valid_session
        response.should redirect_to(percentage_modifier)
      end
    end

    describe "with invalid params" do
      it "assigns the percentage_modifier as @percentage_modifier" do
        percentage_modifier = PercentageModifier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PercentageModifier.any_instance.stub(:save).and_return(false)
        put :update, {:id => percentage_modifier.to_param, :percentage_modifier => {}}, valid_session
        assigns(:percentage_modifier).should eq(percentage_modifier)
      end

      it "re-renders the 'edit' template" do
        percentage_modifier = PercentageModifier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PercentageModifier.any_instance.stub(:save).and_return(false)
        put :update, {:id => percentage_modifier.to_param, :percentage_modifier => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested percentage_modifier" do
      percentage_modifier = PercentageModifier.create! valid_attributes
      expect {
        delete :destroy, {:id => percentage_modifier.to_param}, valid_session
      }.to change(PercentageModifier, :count).by(-1)
    end

    it "redirects to the percentage_modifiers list" do
      percentage_modifier = PercentageModifier.create! valid_attributes
      delete :destroy, {:id => percentage_modifier.to_param}, valid_session
      response.should redirect_to(percentage_modifiers_url)
    end
  end

end
